SELECT * FROM EMPLOYEES;

SELECT 10 + 20 FROM DUAL;
SELECT 10 + NULL FROM DUAL;

-- ORACLE 문자열 결합 : || 사용
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES;

-- CHR
SELECT CHR(65), CHR(97) FROM DUAL;

-- LOWER, UPPER
SELECT UPPER(FIRST_NAME), LOWER(FIRST_NAME) FROM EMPLOYEES;

SELECT LTRIM('      홍길동') FROM DUAL; -- 왼쪽에서 공백 제거
SELECT LTRIM('홍길동', '홍') FROM DUAL; --왼쪽에서 홍 제거
SELECT LTRIM('홍길동', '홍길') FROM DUAL; --왼쪽에서 홍과 길을 순서대로 제거
SELECT LTRIM('홍길동', '홍동') FROM DUAL; --왼쪽에서 홍과 동을 순서대로 제거
SELECT LTRIM('홍길동', '동홍') FROM DUAL; --왼쪽에서 동과 홍을 순서대로 제거

SELECT LENGTH('아이유         ') FROM DUAL;  
SELECT LENGTH(RTRIM('아이유         ')) FROM DUAL; -- 오른쪽에서 공백 제거
SELECT RTRIM('아이유', '유') FROM DUAL;  
SELECT RTRIM('아이유', '이유') FROM DUAL;
SELECT RTRIM('아이유', '유이') FROM DUAL;
SELECT RTRIM('아이유', '유이아') FROM DUAL;
SELECT RTRIM('아이유', '아이유') FROM DUAL;

SELECT TRIM(TRAILING '유' FROM '아이유') FROM DUAL;
SELECT TRIM(LEADING '아' FROM '아이유') FROM DUAL;
SELECT TRIM(BOTH '아' FROM '아이유이아') FROM DUAL;

SELECT SUBSTR('가나다라바마사아자차카타파하', 3) FROM DUAL;
SELECT SUBSTR('가나다라바마사아자차카타파하', 3, 5) FROM DUAL;

SELECT LENGTH('가나다라바마사아자차카타파하') FROM DUAL;

SELECT REPLACE('가나다라바마사아자차카타파하', '사아자차') FROM DUAL;
SELECT REPLACE('가나다라바마사아자차카타파하', '사아자차', '1234') FROM DUAL;

SELECT LPAD('ABC', 10, '*') FROM DUAL;
SELECT RPAD('ABC', 10, '*') FROM DUAL;

SELECT ABS(-10), ABS(10), SIGN(-10), SIGN(0), SIGN(10) FROM DUAL;

SELECT ROUND(16352.72648), ROUND(16352.72648, 2), ROUND(16352.72648, -2) FROM DUAL;
SELECT TRUNC(16352.72648), TRUNC(16352.72648, 2), TRUNC(16352.72648, -2) FROM DUAL;

SELECT CEIL(16352.72648), FLOOR(16352.72648) FROM DUAL;
SELECT CEIL(12.34), FLOOR(12.34) FROM DUAL;
SELECT CEIL(-12.34), FLOOR(-12.34) FROM DUAL;

SELECT MOD(10, 3) FROM DUAL;
SELECT MOD(10, -3) FROM DUAL;
SELECT MOD(-10, 3) FROM DUAL;
SELECT MOD(-10, -3) FROM DUAL;

SELECT SYSDATE FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;
SELECT ADD_MONTHS('2024-08-31', 1) FROM DUAL;

-- SELECT 'AA' + 'BB' FROM DUAL;
SELECT '22' + '33' FROM DUAL;
SELECT TO_NUMBER('22') + TO_NUMBER('33') FROM DUAL;

SELECT 22 || 33 FROM DUAL;
SELECT TO_CHAR(111) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL;
SELECT TO_DATE('20240821132119', 'YYYYMMDDHH24MISS') A,
       EXTRACT(HOUR FROM TO_TIMESTAMP('20240821132119', 'YYYYMMDDHH24MISS')) B,
       EXTRACT(MINUTE FROM TO_TIMESTAMP('20240821132119', 'YYYYMMDDHH24MISS')) C,
       EXTRACT(SECOND FROM TO_TIMESTAMP('20240821132119', 'YYYYMMDDHH24MISS')) D
       FROM DUAL;
       
SELECT COMMISSION_PCT FROM EMPLOYEES;
SELECT NVL(COMMISSION_PCT, 0) CPCT, 
       NVL2(COMMISSION_PCT, '영업직', '비영업직') "IS_SALES"
FROM EMPLOYEES;

SELECT NULLIF('ABC', 'ABC') FROM DUAL;
SELECT NULLIF('ABC', 'ABC1') FROM DUAL;

SELECT COALESCE(NULL, NULL, NULL, 'A', 'C') FROM DUAL;
SELECT COALESCE(NULL, NULL, NULL) FROM DUAL;
-- SELECT COALESCE('HOME', 'MOBILE', 'OFFICE', 'EMAIL') FROM EMP;

SELECT * FROM DEPARTMENTS;
SELECT 
    DEPARTMENT_NAME,
    CASE DEPARTMENT_ID
         WHEN 10 THEN '관리'
         WHEN 20 THEN '마케팅'
         WHEN 60 THEN 'IT'
         ELSE '기타'
    END AS 한국어부서명,
    CASE 
         WHEN DEPARTMENT_ID = 10 THEN '관리'
         WHEN DEPARTMENT_ID = 20 THEN '마케팅'
         WHEN DEPARTMENT_ID = 60 THEN 'IT'
         ELSE '기타'
    END AS 한국어부서명2 
FROM DEPARTMENTS;

SELECT NVL(DECODE(DEPARTMENT_ID, 10, '관리', 
                                 20, '마케팅', 
                                 30, '구매'), '기타') 한국어부서명
FROM DEPARTMENTS;

SELECT *
FROM EMPLOYEES
-- WHERE COMMISSION_PCT != NULL;
WHERE COMMISSION_PCT IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE NOT (COMMISSION_PCT IS NULL);

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT 'A', 1 FROM DUAL
UNION ALL
SELECT 1, 'A' FROM DUAL;








