-- 테이블 만들기
CREATE TABLE NEWBOOK
(
    BOOKID NUMBER /* PRIMARY KEY */ ,          -- MYSQL : INT, SHORT, TINYINT, FLOAT, ...
    BOOKNAME VARCHAR2(20),  -- MYSQL : VARCHAR
    PUBLISHER VARCHAR2(20),
    PRICE NUMBER
    -- , PRIMARY KEY (BOOKID)
    , CONSTRAINT PK_NEWBOOK PRIMARY KEY (BOOKID)
);
DESC NEWBOOK;
DROP TABLE NEWBOOK; -- 테이블 삭제

-- 테이블 만들기 2
CREATE TABLE NEWCUSTOMER
(
    CUSTID NUMBER PRIMARY KEY
    , NAME VARCHAR2(40)
    , ADDRESS VARCHAR2(40)
    , PHONE VARCHAR2(30)
);
DESC NEWCUSTOMER;

SELECT SYSDATE FROM DUAL; -- DUAL : 임시테이블, 구문의 형식을 갖추기 위해 사용

-- 테이블 만들기 3
CREATE TABLE NEWORDERS
(
    ORDERID NUMBER
    , CUSTID NUMBER
    , BOOKID NUMBER
    , SALEPRICE NUMBER CHECK (SALEPRICE >= 0)
    , ORDERDATE DATE DEFAULT (SYSDATE)
    , PRIMARY KEY (ORDERID)
    , FOREIGN KEY (CUSTID) REFERENCES NEWCUSTOMER(CUSTID)
    , CONSTRAINT FK_NEWBOOK_NEWORDERS FOREIGN KEY (BOOKID) REFERENCES NEWBOOK(BOOKID)
);
DESC NEWORDERS;


-- 테이블 수정

DROP TABLE NEWORDERS;
DROP TABLE NEWBOOK;

CREATE TABLE NEWBOOK
(
    BOOKID NUMBER
    , BOOKNAME VARCHAR2(20)
    , PUBLISHER VARCHAR2(20)
    , PRICE NUMBER
);

ALTER TABLE NEWBOOK ADD ISBN VARCHAR2(13);

ALTER TABLE NEWBOOK MODIFY ISBN NUMBER;

ALTER TABLE NEWBOOK DROP COLUMN ISBN;

ALTER TABLE NEWBOOK MODIFY BOOKID NUMBER NOT NULL;

ALTER TABLE NEWBOOK ADD CONSTRAINT PK_NEWBOOK PRIMARY KEY (BOOKID);
-- ALTER TABLE NEWBOOK ADD PRIMARY KEY (BOOKID);











